### PR TITLE
Ansible Bender Support

### PR DESCRIPTION
**Pull request by LukeShortCloud**
Using Ansible Bender [1] and an Ansible playbook [2] it is possible to re-use this role to build a code-server container image. I had to make a few tweaks, primarily around avoiding systemd restarts and doing healthchecks on the application during the build process. Ansible does not support skipping handlers so the end solution was to remove them entirely. This is a problem we face in the upstream TripleO project as well. The workflow to use `ansible-bender` is as follows:

```
$ ansible-galaxy install git+https://github.com/ekultails/ansible-role-code-server.git,ansible-bender
$ ansible-bender build ./playbook.yaml --extra-ansible-args="--skip-tags service,tests" --squash --no-cache
```

I verified this works by building and pushing an image `ekultails/code-server-demo:centos-8.2` to Red Hat Quay.io. [3]

As a side note, it would be great to see some Molecule tests [4] added to this repository.

1. https://ansible-community.github.io/ansible-bender/build/html/index.html
2. https://gist.github.com/ekultails/1c52735efd79d9b35a9e98e82e9ee5db
3. https://quay.io/repository/ekultails/code-server-demo?tab=tags
4. https://molecule.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by pallxk** [comment]
Wow! A big thanks for your detailed PR! :heart:

The tags and configurable install prefix parts are excellent.

As to the handler part, I agree with you that Ansible currently does not support skipping handlers by tags. But registering all triggering tasks and checking for their changed status seem a little cumbersome and prone to missing some of them to me. I've then searched around, and found some [workarounds](https://stackoverflow.com/a/42429527/3463091). Sadly we have to work around it...

I guess I would add another service-tagged task to set a local variable, and then use that as the condition of the handler. What's your thoughts? You can leave that part to me, or do it if you want.


And thanks for the molecule tests advice, I was thinking about adding tests for a long time, but didn't find an appropriate time to do the actual work. I'll definitely add them hopefully in a near future.

**Comment by LukeShortCloud** [comment]
@pallxk Thanks for the feedback! I agree that the registers may not be the most optimal way. I will send a new revision new week based on one of the other suggestions. I can also investigate adding Molecule tests.

**Comment by pallxk** [comment]
Hi @ekultails, It's been a long time and I've pushed some changes I've proposed to your branch. Hope you don't mind it. If you're fine with my changes, I'm going to merge this. Thanks for your great patch again!

**Comment by LukeShortCloud** [comment]
@pallxk Thanks so much for updating that! Sorry for the delayed response, things have been very busy in my life. Looks good to me!

**Pull request merged**
